
play_again = "yes"
while (play_again == "yes"): 
    #Get user inputs
    stu_name=input("Enter the student name ")

    print("                                        Hi",stu_name,"Welcome to GameInt.\n")
    print("Guess the 4 digit secret colour code using numbers between 1 - 6. You will get only 8 chances.\n")

    #Colour mapping
    print("                                                                  Colour Mapping:")
    print("                                                                  1 - White, 2 - Blue, 3 - Red,")
    print("                                                                  4 - Yellow, 5 - Green, 6 - Purple.")
    print()

    #Creating variables
    attempts=1
    user_list=[]
    digit1=0
    digit2=0
    digit3=0
    digit4=0
    zero_list = [0,0,0,0]
    score=100
    rst1=""
    rst2=""
    rst3=""
    rst4=""

    #Selecting random 4 digits between 1 and 6
    import random
    random_list=[]
    for i in range(0,4):
        n = random.randint(1,6)
        random_list.append(n)
    
    print("Number to Guess - XXXX")
    print()
    print("                 Attempt No                 Guess                     Result")
    print("_______________________________________________________________________________")
    print()


    #Process
    while attempts <= 8:
        #Getting inputs
        digit1=int(input("Enter a number: "))
        digit2=int(input("Enter a number: "))
        digit3=int(input("Enter a number: "))
        digit4=int(input("Enter a number: "))

        #Showing an error message when the user inputs a number greater than 6
        if digit1 <=6:
             user_list.append(digit1)
        else:
            print('Entered number is out of range')
            continue
         
        if digit2 <=6:
             user_list.append(digit2)
        else:
            print('Entered number is out of range')
            continue
        
        if digit3 <=6:
             user_list.append(digit3)
        else:
            print('Entered number is out of range')
            continue
        
        if digit4 <=6:
             user_list.append(digit4)
        else:
            print('Entered number is out of range')
            continue
         
         
        
        print("_______________________________________________________________________________")
        print("                    ",attempts,"                ",user_list,"                  ")
        print("                                                                               ")

        
        #Ending the game when the user input 0000
        if user_list == zero_list:
            print("You ended the game")
            break

        #Printing 1111 when the user inserted numbers are matched with the random numbers generated by the system
        if user_list == random_list:
            print("                                                                      1 1")
            print("                                                                      1 1")
            print()

        #Creating a score system based on the number of attempts he took to succeed      
            score=score-12.5*(attempts-1)

        #Ending messages of the game
            print("Congratulations !!!!! You have won the game…")
            print("You have scored",score,"points.")
            print("Thank you for playing the game")
            break
            
                

        #Compare the guessed 4 digits and random list
        if user_list[0] == random_list[0]:
            rst1="1"
        elif user_list[0] in random_list:
            rst1="0"
        else:
            rst1="."

        if user_list[1] == random_list[1]:
             rst2="1"
        elif user_list[1] in random_list:
             rst2="0"
        else:
            rst2="."

        if user_list[2] == random_list[2]:
             rst3="1"
        elif user_list[2] in random_list:
             rst3="0"
        else:
             rst3="."

        if user_list[3] == random_list[3]:
             rst4="1"
        elif user_list[3] in random_list:
             rst4="0"
        else:
             rst4="."

        user_list =[]
        attempts=attempts+1
        print("                                                                     ",rst1,rst2)
        print("                                                                     ",rst3,rst4)
        print("_________________________________________________________________________________")

        
        
    play_again ="no"
    play_again = str(input("Do you want to play another game (yes/no) ?: "))
    print("_______________________________________________________________________________")
    continue
    

    
    
        
    
    





    
